In [3]:
import numpy as np

# Create a 1D array
python_list = [1,2,3,4,5]
print(type(python_list))
numpy_array = np.array(python_list)
print(type(numpy_array))
print("1D Array:", numpy_array)

<class 'list'>
<class 'numpy.ndarray'>
1D Array: [1 2 3 4 5]


In [4]:
# Create a 2D array
python_list = [[1,2,3], [4,5,6], [7,8,9]]
numpy_array = np.array(python_list)
print("2D Array:\n", numpy_array)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Element-wise addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print("Array Addition:", result)

Array Addition: [5 7 9]


In [6]:
# Reshaping a 1D array into a 2D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, 3)
print("Reshaped 2D Array:\n", arr_2d)

Reshaped 2D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
# Indexing a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
print("Element at row 1, column 2:", arr_2d[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6


In [8]:
# Create a 2D array with random values
arr = np.random.rand(2, 3)
print("Random 2D Array:\n", arr)

Random 2D Array:
 [[0.63407277 0.52860243 0.13213704]
 [0.65599105 0.57521794 0.06477878]]


In [9]:
# Create a 2D array with zeros
arr = np.zeros((2, 3))
print("Zeros 2D Array:\n", arr)

Zeros 2D Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Create a 2D array with a specific value
arr = np.full((2, 3), 5)
print("Specific Value 2D Array:\n", arr)

Specific Value 2D Array:
 [[5 5 5]
 [5 5 5]]


In [11]:
# Concatenating arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))
print("Concatenated Array:", result)

Concatenated Array: [1 2 3 4 5 6]


In [12]:
# Filtering elements based on a condition
arr = np.array([1, 2, 3, 4, 5])
condition = arr > 3
filtered_array = arr[condition]
print("Filtered Array:", filtered_array)

Filtered Array: [4 5]


In [13]:
# Matrix multiplication
# Result[0, 0] = (1*5) + (2*7) = 5 + 14 = 19
# Result[0, 1] = (1*6) + (2*8) = 6 + 16 = 22
# Result[1, 0] = (3*5) + (4*7) = 15 + 28 = 43
# Result[1, 1] = (3*6) + (4*8) = 18 + 32 = 50

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print("Matrix Multiplication Result:\n", result)

Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [14]:
# Calculate sum of elements
arr = np.array([1, 2, 3, 4, 5])
sum = np.sum(arr)
print("Sum of Elements:", sum)

Sum of Elements: 15


In [15]:
# Calculating mean and standard deviation
arr = np.array([1, 2, 6, 7, 9])
mean = np.mean(arr)
std_dev = np.std(arr)
print("Mean:", mean, "Standard Deviation:", std_dev)

Mean: 5.0 Standard Deviation: 3.03315017762062


In [16]:
# Calculate median
arr = np.array([1, 2, 6, 7, 9])
median = np.median(arr)
print("Median:", median)

Median: 6.0


In [17]:
# Calculate correlation coefficient
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
correlation = np.corrcoef(arr1, arr2)
print("Correlation Coefficient:\n", correlation[0,1])

Correlation Coefficient:
 -0.9999999999999999


In [18]:
# Calculate 50th percentile (median)
arr = np.array([1, 2, 3, 4, 5])
percentile_50 = np.percentile(arr, 50)
print("50th Percentile (Median):", percentile_50)

50th Percentile (Median): 3.0


In [19]:
# Calculate quartiles
arr = np.array([1, 2, 3, 4, 5])
quartiles = np.percentile(arr, [25, 50, 75])
print("Quartiles:", quartiles)

Quartiles: [2. 3. 4.]


In [20]:
# Calculate standard error
arr = np.array([1, 2, 3, 4, 5])
std_err = np.std(arr) / np.sqrt(len(arr))
print("Standard Error:", std_err)

Standard Error: 0.6324555320336759


In [21]:
# Calculate variance
arr = np.array([1, 2, 3, 4, 5])
variance = np.var(arr)
print("Variance:", variance)

Variance: 2.0


In [22]:
# Calculate covariance
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])
covariance = np.cov(x, y)[0, 1]
print("Covariance:", covariance)

Covariance: -2.5
